dist: xenial
language: minimal

git:
  depth: 3

services:
    - docker

cache:
  directories:
    - /home/travis/docker

env:
  global:
  - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
  - IMAGE=rpi-buster


before_script:
  - image=$(find $PWD -type f -name "*.rpi-buster")
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker build . -t ${IMAGE}:latest -f ${image}

script:
    - docker run -it -v $PWD:/Flir-Lepton ${IMAGE}:latest bash  -c "cd Flir-Lepton; ./build.sh"
    - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT}  | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi

notifications:
  email:
    on_success: change
    on_failure: always